use std::collections::HashMap;

use dyn_fmt::AsStrFormatExt;
use nestify::nest;
use regex::Regex;
use serde::{Deserialize, Serialize};
use tokio::{fs, io::AsyncWriteExt};
use toml_edit::{Array, Item, Table, Value};

use crate::utils::{deserialize_regex_vec, serialize_regex_vec};
use crate::{
    Result,
    ui::diffs::{DiffChange, ProductDiff, ProductDiffs},
};

type ProductKeyPair<'T> = (&'T String, &'T Product);

nest! {
    #[derive(Default, Debug, Clone, Serialize, Deserialize)]*
    #[serde(rename_all = "kebab-case")]*
    pub struct VCSProducts {
        pub metadata: pub struct Metadata {
            pub universe_id: u64,
            pub luau_file: Option<String>,
            pub discount_prefix: Option<String>,
            #[serde(default, deserialize_with = "deserialize_regex_vec", serialize_with = "serialize_regex_vec")]
            pub name_filters: Option<Vec<Regex>>,
        },

        #[serde(default)]
        pub gamepasses: HashMap<String, pub struct Product {
            pub id: Option<u64>,
            pub name: String,
            pub prefix: Option<String>,
            pub description: Option<String>,
            pub active: bool,
            pub discount: Option<u8>,
            pub price: i64,
            pub regional_pricing: Option<bool>,
        }>,

        #[serde(default)]
        pub products: HashMap<String, Product>,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum ProductType {
    GamePass,
    DevProduct,
}
pub enum MultiProduct {
    GamePass(Product),
    DevProduct(Product),
}

macro_rules! check_diff {
    ($diffs:expr, $field:expr, $old:expr, $new:expr, $variant:ident) => {
        if $old != $new {
            $diffs.push(DiffChange::Changed(ProductDiff::$variant(
                $old.clone(),
                $new.clone(),
            )));
        } else {
            $diffs.push(DiffChange::Unchanged(ProductDiff::$variant(
                $old.clone(),
                $new.clone(),
            )));
        }
    };
}

impl VCSProducts {
    pub async fn get_products() -> Result<Self> {
        let file_data = fs::read("products.toml").await?;
        let products: VCSProducts = toml::from_slice(&file_data)?;
        Ok(products)
    }

    pub async fn save_products(&self) -> Result<()> {
        let mut toml_products: toml_edit::DocumentMut;

        if let Ok(data) = fs::read("products.toml").await {
            let document_string = String::from_utf8(data.clone())?;
            toml_products = document_string.parse()?;
        } else {
            toml_products = toml_edit::DocumentMut::new();
        }

        let metadata = section(&mut toml_products, "metadata");

        set_or_remove(
            metadata,
            "discount-prefix",
            self.metadata.discount_prefix.clone(),
        );
        set_value(metadata, "universe-id", self.metadata.universe_id as i64);
        set_or_remove(metadata, "luau-file", self.metadata.luau_file.clone());

        let filters = self
            .metadata
            .name_filters
            .clone()
            .unwrap_or_default()
            .iter()
            .map(|x| x.as_str().to_string())
            .collect::<Vec<_>>();

        set_value(metadata, "name-filters", Array::from_iter(filters.iter()));

        let gamepasses = section(&mut toml_products, "gamepasses");
        for (key, gamepass) in &self.gamepasses {
            update_product_table(gamepasses, key, gamepass);
        }

        let products = section(&mut toml_products, "products");
        for (key, product) in &self.products {
            update_product_table(products, key, product);
        }

        fs::write("products.toml", toml_products.to_string()).await?;
        Ok(())
    }

    pub async fn serialize_luau(&self) -> Result<()> {
        let products_lua_file = match self.metadata.luau_file.clone() {
            Some(file) => file,
            None => return Ok(()),
        };

        let mut file = fs::File::create(products_lua_file).await?;
        let mut contents = String::new();

        let serialize = |contents: &mut String, products: &HashMap<String, Product>| {
            let mut values: Vec<ProductKeyPair<'_>> = products.into_iter().collect();

            values.sort_by(|a: &ProductKeyPair<'_>, b: &ProductKeyPair<'_>| a.1.id.cmp(&b.1.id));

            for (index, product) in values.iter().enumerate() {
                *contents += &format!(
                    "\t\t[{:?}] = {{ id = {:?}, price = {} }}",
                    product.0,
                    product.1.id.unwrap_or(0),
                    product.1.get_price()
                );

                if index != products.len() - 1 {
                    *contents += ",\n";
                } else {
                    *contents += "\n";
                }
            }
        };

        contents += "-- This file is automatically generated by rbx-products. Do not edit this file directly.\n";
        contents += "export type Product = { id: number, price: number }\n\n";
        contents += "return {\n\tGamepasses = {\n";
        serialize(&mut contents, &self.gamepasses);
        contents += "\t} :: {[string]: Product},\n\n\tProducts = {\n";
        serialize(&mut contents, &self.products);
        contents += "\t} :: {[string]: Product}\n}";

        file.write_all(contents.as_bytes()).await?;

        Ok(())
    }
}

impl Product {
    pub fn has_discount(&self) -> bool {
        if let Some(discount) = self.discount
            && discount > 0
        {
            true
        } else {
            false
        }
    }

    pub fn get_price(&self) -> u64 {
        if let Some(discount) = self.discount
            && discount > 0
        {
            (self.price as f64 * (1.0 - (discount as f64 / 100.0))).floor() as u64
        } else {
            self.price as u64
        }
    }

    pub fn get_title(&self) -> String {
        if self.has_discount() {
            return self.name.clone();
        }

        if let Some(prefix) = &self.prefix {
            format!("{} {}", prefix, self.name)
        } else {
            self.name.clone()
        }
    }

    pub fn diff(&self, other: &Self, metadata: Option<&Metadata>) -> Option<ProductDiffs> {
        let mut diffs = vec![] as Vec<DiffChange>;

        let title = if let Some(metadata) = metadata {
            if let (Some(discount), Some(prefix)) = (self.discount, &metadata.discount_prefix) {
                format!("{} {}", prefix.format(&[discount]), self.get_title())
            } else {
                self.get_title()
            }
        } else {
            self.get_title()
        };

        let active = self.active;
        let price = self.get_price();
        let description = self.description.clone().unwrap_or(String::default());

        check_diff!(diffs, Title, other.name, title, Title);
        check_diff!(
            diffs,
            Description,
            other.description.clone().unwrap(),
            description,
            Description
        );
        check_diff!(diffs, Price, other.price as u64, price, Price);
        check_diff!(
            diffs,
            RegionalPricing,
            other.regional_pricing.unwrap_or(false),
            self.regional_pricing.unwrap_or(false),
            RegionalPricing
        );
        check_diff!(diffs, Active, other.active, active, Active);

        let has_diffs = diffs.iter().any(|d| match d {
            DiffChange::Changed(_) => true,
            _ => false,
        });

        if has_diffs {
            Some(ProductDiffs {
                name: self.name.clone(),
                id: self.id.unwrap_or(0) as u64,
                diffs,
            })
        } else {
            None
        }
    }
}

impl Product {
    fn apply_to_table(&self, table: &mut Table) {
        set_or_remove(table, "id", self.id.map(|id| id as i64));
        set_or_remove(table, "prefix", self.prefix.clone());
        set_value(table, "name", self.name.clone());
        set_or_remove(table, "description", self.description.clone());
        set_value(table, "active", self.active);
        set_or_remove(table, "discount", self.discount.map(|d| d as i64));
        set_value(table, "price", self.price);
        set_or_remove(table, "regional-pricing", self.regional_pricing);
    }
}

impl From<&Product> for Item {
    fn from(prod: &Product) -> Self {
        let mut table = Table::new();
        prod.apply_to_table(&mut table);
        Item::Table(table)
    }
}

fn section<'a>(doc: &'a mut toml_edit::DocumentMut, name: &str) -> &'a mut Table {
    let item = doc.entry(name).or_insert_with(|| Item::Table(Table::new()));
    if !item.is_table() {
        *item = Item::Table(Table::new());
    }
    item.as_table_mut()
        .expect("item was just ensured to be a table")
}

fn set_value<V: Into<Value>>(table: &mut Table, key: &str, value: V) {
    let existing_decor = table
        .get(key)
        .and_then(Item::as_value)
        .map(|v| v.decor().clone());

    table[key] = toml_edit::value(value);

    if let Some(decor) = existing_decor
        && let Some(new_value) = table[key].as_value_mut()
    {
        *new_value.decor_mut() = decor;
    }
}

fn set_or_remove<V: Into<Value>>(table: &mut Table, key: &str, value: Option<V>) {
    match value {
        Some(value) => set_value(table, key, value),
        None => {
            table.remove(key);
        }
    }
}

fn update_product_table(table: &mut Table, key: &str, product: &Product) {
    match table.get_mut(key).and_then(Item::as_table_mut) {
        Some(existing) => product.apply_to_table(existing),
        None => table[key] = product.into(),
    }
}
